Added tests for setup-ssh action

diff --git a/.github/actions/setup-ssh/action.yml b/.github/actions/setup-ssh/action.yml
--- a/.github/actions/setup-ssh/action.yml
+++ b/.github/actions/setup-ssh/action.yml
@@ -33,27 +33,27 @@ runs:
         KEY: ${{ inputs.private-key }}
         KEY_NAME: ${{ inputs.private-key-name }}
       run: |
-        echo "$KEY" > ~/.ssh/$KEY_NAME
-        chmod 600 ~/.ssh/$KEY_NAME
-        echo "path=~/.ssh/$KEY_NAME" >> $GITHUB_OUTPUT
+        path="$HOME/.ssh/$KEY_NAME"
+        echo "$KEY" > "$path"
+        chmod 600 "$path"
+        echo "path=$path" >> $GITHUB_OUTPUT
     - name: Check passphrase
       shell: bash
       env:
-        PASSPHRASE: ${{ inputs.private-key-passphrase }}
-        KEY_PATH: ${{ steps.pk.outputs.path }}
+        PASSPHRASE: "${{ inputs.private-key-passphrase }}"
+        KEY_PATH: "${{ steps.pk.outputs.path }}"
       run: |
         # Try to decrypt the private key with the provided passphrase (if any)
-        if ! ssh-keygen -y -P "$PASSPHRASE" -f "$KEY_PATH" &> /dev/null; then
+        if ! ssh-keygen -y -P "$PASSPHRASE" -f "$KEY_PATH" > /dev/null; then
           # If no passphrase is provided, warn that the private key might need one
           if [[ -z "$PASSPHRASE" ]]; then
-            echo "::warning::The provided 'private-key' is passphrase-protected, but no 'private-key-passphrase' was provided. SSH commands may fail."
+            msg="The provided 'private-key' is passphrase-protected, but no 'private-key-passphrase' was provided."
           else
-            # If the passphrase is provided then it is incorrect. Fail with an error
-            echo "::error::The provided 'private-key-passphrase' is incorrect for the provided 'private-key'."
-            exit 1
+            msg="The provided 'private-key-passphrase' is incorrect for the provided 'private-key'."
           fi
+          echo "::error::$msg"
+          exit 1
         fi
-
     # For security reasons, ssh-add doesn't allow to pass the passphrase from stdin,
     # therefore we must use expect (https://gist.github.com/matthiasbalke/f0abe1e6c18704f086389009075c645e)
     - name: Add passphrase to ssh-agent
@@ -70,7 +70,7 @@ runs:
         expect -c "
           spawn ssh-add \"$KEY_PATH\"
           expect \"Enter passphrase for *\"
-          send \"${PASSPHRASE}\n\"
+          send \"${PASSPHRASE}\r\"
           expect \"Identity added: *\"
         "
         # Export SSH_AUTH_SOCK and SSH_AGENT_PID to the environment so subsequent steps
