setup-ssh: Add retry to ssh-keyscan (#54)

diff --git a/.github/actions/setup-ssh/action.yml b/.github/actions/setup-ssh/action.yml
--- a/.github/actions/setup-ssh/action.yml
+++ b/.github/actions/setup-ssh/action.yml
@@ -85,6 +85,11 @@ runs:
         HOSTS: ${{ inputs.hosts }}
       run: |
         for host in $HOSTS; do
-          ssh-keyscan $host >> ~/.ssh/known_hosts
+          # Retry once if ssh-keyscan fails to try avoid transient errors
+          if ! ssh-keyscan $host >> ~/.ssh/known_hosts; then
+            echo "Retrying ssh-keyscan for $host in 5s..."
+            sleep 5
+            ssh-keyscan $host >> ~/.ssh/known_hosts
+          fi
         done
         chmod 600 ~/.ssh/known_hosts
