Added pyproject_toml_dir input

diff --git a/.github/workflows/publish-python-package/publish-python-package.yml b/.github/workflows/publish-python-package/publish-python-package.yml
--- a/.github/workflows/publish-python-package/publish-python-package.yml
+++ b/.github/workflows/publish-python-package/publish-python-package.yml
@@ -2,6 +2,11 @@ name: Publish Python package
 on:
   workflow_call:
     inputs:
+      pyproject_toml_dir:
+        type: string
+        required: false
+        default: ""
+        description: "The directory where the pyproject.toml file is located, relative to the repository top-level directory."
       pypi_package:
         type: boolean
         required: false
@@ -34,10 +39,37 @@ env:
   ARTIFACT_NAME: _dist_artifact
       
 jobs:
+  set_pyproject_toml_dir:
+    name: Check pyproject.toml directory
+    runs-on: ubuntu-latest
+    outputs:
+      pyproject_toml_dir: ${{ steps.set-pyproject-toml-dir.outputs.pyproject_toml_dir }}
+    steps:
+      - uses: actions/checkout@v5
+
+      - name: Set pyproject.toml directory
+        id: set-pyproject-toml-dir
+        run: |
+          if [ -z '${{ inputs.pyproject_toml_dir }}' ]; then
+            pyproject_toml_dir='.'
+          else
+            pyproject_toml_dir='${{ inputs.pyproject_toml_dir }}'
+          fi
+          if [ ! -d "$pyproject_toml_dir" ]; then
+            echo "::error Directory '$pyproject_toml_dir' not found in the current repository"
+            exit 1
+          fi
+          if [ ! -f "$pyproject_toml_dir/pyproject.toml" ]; then
+            echo "::error 'pyproject.toml' not found in '${{ inputs.pyproject_toml_dir }}'"
+            exit 1
+          fi
+          echo "pyproject_toml_dir=$pyproject_toml_dir" >> $GITHUB_OUTPUT
+          echo "pyproject.toml found in '$pyproject_toml_dir'"
+
   build_tarball_and_python_wheel:
     name: Build tarball and Python wheel
     runs-on: ubuntu-latest
-    needs: get_latest_compatible_python_version
+    needs: set_pyproject_toml_dir
     steps:
       - uses: actions/checkout@v5
 
@@ -47,7 +79,10 @@ jobs:
         run: python -m pip install build ${{ inputs.pypi_package == 'true' && "twine" || "" }}
 
       - name: Build distributions
-        run: pyproject-build ${{ inputs.pypi_package != 'true' && "--sdist" || "" }} --outdir ${{ env.PYTHON_ARTIFACT_DIR }}
+        run: |
+          pyproject-build '${{ inputs.pypi_package != 'true' && "--sdist" || "" }}' \
+            --outdir '${{ env.PYTHON_ARTIFACT_DIR }}'
+            --src '${{ needs.set_pyproject_toml_dir.outputs.pyproject_toml_dir }}'
 
       - uses: actions/upload-artifact@v4
         with:
