Updated action with url

diff --git a/.github/actions/comment/action.yml b/.github/actions/comment/action.yml
--- a/.github/actions/comment/action.yml
+++ b/.github/actions/comment/action.yml
@@ -74,23 +74,60 @@ runs:
       # We use the +H option to prevent history expansion, so the '!' character can be printed out without 
       # problems.
       run: |
+        # Parse URL
+        if [[ -n "${{ inputs.url }}" ]]; then
+          url= xargs <<< "${{ inputs.url }}" # Remove leading/trailing whitespaces
+          # Regex for the url in an expanded form
+          regex='^'                             # Beginning of string anchor
+          regex+='https://github\.com/'         # Github URL
+          regex+='([^/ ]+)'                     # Match any non-space/non-slash characters - Capture group 1 (the OWNER)
+          regex+='/'                            # Match a forward slash
+          regex+='([^/ ]+)'                     # Match any non-space/non-slash characters - Capture group 2 (the REPO)
+          regex+='/'                            # Match a forward slash
+          regex+='issues/'                      # Match "issues/"
+          regex+='([0-9]+)'                     # Match one or more digits - Capture group 3 (the NUMBER)
+          regex+='(#issuecomment-([0-9]+))?'    # Optionally match "#issuecomment-" and one or more digits - Capture group 5 (the COMMENT-ID)
+          regex+='$'                            # End of string anchor
+          if [[ "$1" =~ $regex ]]; then
+            OWNER=${BASH_REMATCH[1]}
+            REPOSITORY=${BASH_REMATCH[2]}
+            NUM=${BASH_REMATCH[3]}
+            COMMENT_ID=${BASH_REMATCH[5]}
+          else
+            echo "::error::Invalid URL \"${{ inputs.url }}\". Please provide a valid URL format."
+            exit 1
+          fi
+        fi
+
         # Set NUMBER
         if [[ ${{ inputs.number }} == 0 ]]; then # If number is not provided (number type defaults to 0 -- https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs)
-          if [[ -n "${{ github.event.issue }}" ]]; then
+          if [[ -n "$NUMBER" ]]; then # If url is provided
+            echo "NUMBER=$NUMBER" >> $GITHUB_ENV
+          if [[ -n "${{ github.event.issue }}" ]]; then # If in an issue event
             echo "NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
-          elif [[ -n "${{ github.event.pull_request }}" ]]; then
+          elif [[ -n "${{ github.event.pull_request }}" ]]; then # If in a pull_request event
             echo "NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
           else
             echo "::error::Couldn't infer PR/Issue number from the event payload, please enter PR/Issue number as an input."
             exit 1
           fi
+        elif [[ -n "${NUMBER}" ]]; then # If both number and url are provided
+          echo "::error::Cannot use 'number' and 'url' together. Please provide only one of them."
+          exit 1
         else
           echo "NUMBER=${{ inputs.number }}" >> $GITHUB_ENV
         fi
 
         # Set REPO
-        repo_name=${{ inputs.repo }}
-        echo "REPO=${repo_name:-${{github.repository}}}" >> $GITHUB_ENV
+        if [[ -n "${{ inputs.repo }}" && -n "$REPOSITORY" ]]; then # If both repo and url are provided
+            echo "::error::Cannot use 'repo' and 'url' together. Please provide only one of them."
+            exit 1
+        fi
+        REPO_INPUT=${{ inputs.repo }}
+        # If REPOSITORY is set (url is provided), set REPO_URL to $REPOSITORY/$OWNER
+        REPO_URL="${REPOSITORY:+$REPOSITORY/$OWNER}"
+        # If REPO_INPUT is set, use it. Otherwise, use REPO_URL. If REPO_URL is not set, use the default github.repository.
+        echo "REPO=${REPO_INPUT:-${REPO_URL:-${{github.repository}}}}" >> $GITHUB_ENV 
 
         # Set LABEL_STRING
         label=${{ inputs.label }}
@@ -104,7 +141,13 @@ runs:
       shell: bash
       run: |
         if [[ -n "${{ inputs.comment-id }}" ]]; then
+          if [[ -n "$COMMENT_ID" ]]; then # If both comment-id and url (with COMMENT_ID portion) are provided
+            echo "::error::Cannot use 'comment-id' and 'url' (containing the COMMENT_ID portion) together. Please provide only one of them."
+            exit 1
+          fi
           echo "COMMENT_ID=${{ inputs.comment-id }}" >> $GITHUB_ENV
+        elif [[ -n "$COMMENT_ID" ]]; then # If url is provided
+          echo "COMMENT_ID=$COMMENT_ID" >> $GITHUB_ENV
         else
           # if comment-id is not provided, get the comment id from the label (if found)
           id=$(gh api \
