Added step for intermediary artefacts deletion

diff --git a/.github/workflows/publish-python-package.yml b/.github/workflows/publish-python-package.yml
--- a/.github/workflows/publish-python-package.yml
+++ b/.github/workflows/publish-python-package.yml
@@ -52,17 +52,17 @@ jobs:
           if [ -z '${{ inputs.pyproject-toml-dir }}' ]; then
             pyproject_toml_dir='.'
             if [[ ! -f "$pyproject_toml_dir"/pyproject.toml ]]; then
-              echo "::error No 'pyproject.toml' found in the repository top-level folder. To specify a directory for your 'pyproject.toml', please use the 'pyproject-toml-dir' input"
+              echo "::error::No 'pyproject.toml' found in the repository top-level folder. To specify a directory for your 'pyproject.toml', please use the 'pyproject-toml-dir' input"
               exit 1
             fi
           else
             pyproject_toml_dir='${{ inputs.pyproject-toml-dir }}'
             if [[ ! -d "$pyproject_toml_dir" ]]; then
-              echo "::error Specified 'pyproject-toml-dir' directory '$pyproject_toml_dir' not found in the current repository"
+              echo "::error::Specified 'pyproject-toml-dir' directory '$pyproject_toml_dir' not found in the current repository"
               exit 1
             fi
             if [[ ! -f "$pyproject_toml_dir"/pyproject.toml ]]; then
-              echo "::error No 'pyproject.toml' found in the specified 'pyproject-toml-dir' directory '$pyproject_toml_dir'"
+              echo "::error::No 'pyproject.toml' found in the specified 'pyproject-toml-dir' directory '$pyproject_toml_dir'"
               exit 1
             fi
           fi
@@ -193,6 +193,8 @@ jobs:
     name: Upload artifact with tarball and built packages
     runs-on: ubuntu-latest
     needs: [publish-pypi-package, publish-conda-package]
+    env:
+      GH_TOKEN: ${{ github.token }}
     outputs:
       artifact-name: ${{ steps.set-output-artifact-name.outputs.artifact-name }}
     steps:
@@ -210,17 +212,23 @@ jobs:
           name: ${{ env.CONDA_ARTIFACT_NAME }}
           path: ${{ env.CONDA_ARTIFACT_DIR }}
         
-    #   # To avoid having intermediary artifacts from previous steps
-    #   # we delete the python and conda artifacts
-    #   - name: Delete artifacts
-    #     env:
-    #       GH_TOKEN: ${{ github.token }}
-    #     run: |
-    #       # Get the python artifact ID
-    #       artifact_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
-    #         --jq '.artifacts[] | select(.name=="${{ env.PYTHON_ARTIFACT_NAME }}") | .id')
-    #       # Delete the artifact
-    #       gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
+      # To avoid having intermediary artifacts from previous steps
+      # we delete the python and conda artifacts
+      - name: Delete artifacts
+        run: |
+          for artifact_name in '${{ env.PYTHON_ARTIFACT_NAME }}' '${{ env.CONDA_ARTIFACT_NAME }}'; do
+            # Get the artifact ID
+            artifact_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
+                --jq ".artifacts[] | select(.name==\"$artifact_name\") | .id")
+            # Delete the artifact
+            if [ -n "$artifact_id" ]; then
+                gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id &> /dev/null \
+                  && echo "Deleted artifact '$artifact_name'." \
+                  || echo "::warning::No permissions to delete artifact '$artifact_name'. Please run the workflow with \`permissions: actions: write\`"
+            else
+                echo "Artifact '$artifact_name' not found."
+            fi
+          done
 
       - name: Create output artifact directory
         run: |
