Fixed pyproject-build command

diff --git a/.github/workflows/publish-python-package.yml b/.github/workflows/publish-python-package.yml
--- a/.github/workflows/publish-python-package.yml
+++ b/.github/workflows/publish-python-package.yml
@@ -33,6 +33,7 @@ env:
   PYTHON_ARTIFACT_NAME: _python_artifact
   PYTHON_ARTIFACT_DIR: _artifact_dir
   ARTIFACT_NAME: _dist_artifact
+  RECIPE_DIR: _recipe_dir
       
 jobs:
   inputs_sanity_check:
@@ -44,6 +45,14 @@ jobs:
       anaconda_username: ${{ steps.check-anaconda-username.outputs.anaconda_username }}
     steps:
       - uses: actions/checkout@v5
+      
+      - name: Check package to publish
+        run: |
+          # Check that at least one of pypi-package or conda-package is true
+          if [ '${{ inputs.pypi-package }}' != 'true' ] && [ '${{ inputs.conda-package }}' != 'true' ]; then
+            echo "::error::At least one of 'pypi-package' or 'conda-package' must be true"
+            exit 1
+          fi
 
       - name: Check pyproject.toml directory
         id: check-pyproject-toml-dir
@@ -104,13 +113,15 @@ jobs:
       - uses: actions/setup-python@v5
         
       - name: Install build dependencies
-        run: python -m pip install build ${{ inputs.pypi-package == 'true' && 'twine' || '' }}
+        run: python -m pip install build ${{ inputs.pypi-package && 'twine' || '' }}
 
       - name: Build distributions
         run: |
-          pyproject-build '${{ inputs.pypi-package != 'true' && '--sdist' || '' }}' \
-            --outdir '${{ env.PYTHON_ARTIFACT_DIR }}'
-            --src '${{ needs.inputs_sanity_check.outputs.pyproject_toml_dir }}'
+          pyproject-build ${{ ! inputs.pypi-package && '--sdist' || '' }} \
+            --outdir '${{ env.PYTHON_ARTIFACT_DIR }}' \
+            '${{ needs.inputs_sanity_check.outputs.pyproject_toml_dir }}'
+          echo Built files:
+          ls -l '${{ env.PYTHON_ARTIFACT_DIR }}' | tail -n -1
 
       - uses: actions/upload-artifact@v4
         with:
@@ -130,6 +141,7 @@ jobs:
         uses: actions/download-artifact@v5
         with:
           name: ${{ env.PYTHON_ARTIFACT_NAME }}
+          path: ${{ env.PYTHON_ARTIFACT_DIR }}
     
       - name: Publish package to PyPI
         uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
@@ -150,6 +162,7 @@ jobs:
         uses: actions/download-artifact@v5
         with:
           name: ${{ env.PYTHON_ARTIFACT_NAME }}
+          path: ${{ env.PYTHON_ARTIFACT_DIR }}
     
       - name: Set up micromamba
         uses: mamba-org/setup-micromamba@v2
@@ -162,14 +175,19 @@ jobs:
             grayskull
       
       - name: Create recipe from tarball
+        id: create-recipe
         run: |
-          grayskull pypi ${{ env.PYTHON_ARTIFACT_DIR }}/*.tar.gz --output recipe_dir
-      
+          mkdir ${{ env.RECIPE_DIR }} && cd ${{ env.RECIPE_DIR }}
+          micromamba run -n build-env grayskull pypi ../${{ env.PYTHON_ARTIFACT_DIR }}/*.tar.gz
+          ls -l
+          echo ============
+          ls -l addmeta
+
       - name: Publish package to Anaconda.org
         id: publish-conda-package
         uses: ACCESS-NRI/action-build-and-upload-conda-packages@v3.0.0
         with:
-          meta_yaml_dir: recipe_dir
+          meta_yaml_dir: ${{ env.RECIPE_DIR }}
           user: '${{ inputs.anaconda-username || secrets.ANACONDA_USERNAME }}'
           token: '${{ inputs.anaconda-token || secrets.ANACONDA_TOKEN }}'
 
